source 'https://rubygems.org'

ruby '2.0.0'

gem 'sinatra'
gem 'sinatra-flash'
gem 'warden'
gem 'thin'
gem 'data_mapper'
gem 'dm-sweatshop'
gem 'dm-postgres-adapter'
gem 'pg'
gem 'grape'
gem 'unicorn'
gem 'rack-block'
gem 'patron'